"""AI module contracts, data structures, and schemas."""

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field

CefrLevel = Literal["A1", "A2", "B1", "B2", "C1", "C2"]
CEFR_LEVELS = ("A1", "A2", "B1", "B2", "C1", "C2")

AiProviderName = Literal["GEMINI", "GROQ"]
AI_PROVIDER_NAMES = ("GEMINI", "GROQ")

TutorQuestionType = Literal[
    "MULTIPLE_CHOICE",
    "CONTEXTUAL_CLOZE",
    "TYPED_RECALL",
    "MICRO_LESSON_RETEST",
]
TUTOR_QUESTION_TYPES = (
    "MULTIPLE_CHOICE",
    "CONTEXTUAL_CLOZE",
    "TYPED_RECALL",
    "MICRO_LESSON_RETEST",
)

OptionId = Literal["A", "B", "C", "D"]
OPTION_IDS = ("A", "B", "C", "D")

RetestType = Literal["CONTEXTUAL_CLOZE", "TYPED_RECALL"]
RETEST_TYPES = ("CONTEXTUAL_CLOZE", "TYPED_RECALL")


class BaseAiModel(BaseModel):
    """Base model with camelCase aliasing support."""

    model_config = ConfigDict(
        populate_by_name=True,
        serialize_by_alias=True,
    )


class TermEnrichmentInput(BaseAiModel):
    """Input payload for enriching a vocabulary term within its original article context."""

    article_id: str = Field(alias="articleId")
    article_title: str = Field(alias="articleTitle")
    term_id: str = Field(alias="termId")
    value: str
    lemma: str
    parent_sentence_text: str = Field(alias="parentSentenceText")
    surrounding_sentence_context: str = Field(alias="surroundingSentenceContext")


class TermExample(BaseAiModel):
    """Bilingual contextual example sentence."""

    sentence: str
    translation_vi: str = Field(alias="translationVi")


class TermEnrichmentResult(BaseAiModel):
    """Structured enrichment metadata generated by the AI provider for a term."""

    part_of_speech: str = Field(alias="partOfSpeech")
    cefr_level: CefrLevel = Field(alias="cefrLevel")
    contextual_meaning_vi: str = Field(alias="contextualMeaningVi")
    definition_en: str = Field(alias="definitionEn")
    contextual_explanation: str = Field(alias="contextualExplanation")
    ipa: str | None = None
    synonyms: list[str] = Field(default_factory=list)
    antonyms: list[str] = Field(default_factory=list)
    collocations: list[str] = Field(default_factory=list)
    related_terms: list[str] = Field(default_factory=list, alias="relatedTerms")
    examples: list[TermExample] = Field(default_factory=list)
    sentence_translation_vi: str = Field(alias="sentenceTranslationVi")


class TutorQuestionCandidate(BaseAiModel):
    """Candidate vocabulary item passed to the AI to construct an interactive question."""

    id: str
    word_display: str = Field(alias="wordDisplay")
    lemma: str
    part_of_speech: str = Field(alias="partOfSpeech")
    meaning_vi: str = Field(alias="meaningVi")
    examples: Any = None


class TutorQuestionInput(BaseAiModel):
    """Request payload sent to the AI service to generate a targeted tutor question."""

    allowlist_ids: list[str] = Field(alias="allowlistIds")
    candidates: list[TutorQuestionCandidate]
    question_type: TutorQuestionType = Field(alias="questionType")


class McOption(BaseAiModel):
    """Single multiple-choice answer option."""

    id: OptionId
    text: str


class BaseTutorQuestionResult(BaseAiModel):
    """Common fields shared by all tutor question generation results."""

    selected_candidate_id: str = Field(alias="selectedCandidateId")
    question_type: TutorQuestionType = Field(alias="questionType")
    question_prompt_vi: str = Field(alias="questionPromptVi")
    explanation_vi: str = Field(alias="explanationVi")
    feedback_correct_vi: str = Field(alias="feedbackCorrectVi")
    feedback_incorrect_vi: str = Field(alias="feedbackIncorrectVi")


class MultipleChoiceResult(BaseTutorQuestionResult):
    """Question result payload for 4-option multiple-choice activities."""

    question_type: Literal["MULTIPLE_CHOICE"] = Field(default="MULTIPLE_CHOICE", alias="questionType")
    options: list[McOption]
    correct_option_id: OptionId = Field(alias="correctOptionId")


class ContextualClozeResult(BaseTutorQuestionResult):
    """Question result payload for fill-in-the-blank contextual cloze activities."""

    question_type: Literal["CONTEXTUAL_CLOZE"] = Field(default="CONTEXTUAL_CLOZE", alias="questionType")
    sentence_with_blank: str = Field(alias="sentenceWithBlank")
    canonical_answer: str = Field(alias="canonicalAnswer")


class TypedRecallResult(BaseTutorQuestionResult):
    """Question result payload for direct typed recall activities."""

    question_type: Literal["TYPED_RECALL"] = Field(default="TYPED_RECALL", alias="questionType")
    recall_prompt_vi: str = Field(alias="recallPromptVi")
    canonical_answer: str = Field(alias="canonicalAnswer")


class MicroLessonRetestResult(BaseTutorQuestionResult):
    """Question result payload for micro-lesson followed by immediate retest."""

    question_type: Literal["MICRO_LESSON_RETEST"] = Field(default="MICRO_LESSON_RETEST", alias="questionType")
    micro_lesson_title: str | None = Field(default=None, alias="microLessonTitle")
    micro_lesson_fact_en: str | None = Field(default=None, alias="microLessonFactEn")
    micro_lesson_fact_vi: str | None = Field(default=None, alias="microLessonFactVi")
    micro_lesson_vi: str = Field(alias="microLessonVi")
    retest_type: RetestType = Field(alias="retestType")
    sentence_with_blank: str | None = Field(default=None, alias="sentenceWithBlank")
    recall_prompt_vi: str | None = Field(default=None, alias="recallPromptVi")
    canonical_answer: str = Field(alias="canonicalAnswer")


TutorQuestionResult = Annotated[
    MultipleChoiceResult | ContextualClozeResult | TypedRecallResult | MicroLessonRetestResult,
    Field(discriminator="question_type"),
]


class WarmupFactStory(BaseAiModel):
    """Intriguing real-world fact or trivia story embedding target vocabulary."""

    title: str
    fact_content_vi: str = Field(alias="factContentVi")
    target_words: list[str] = Field(alias="targetWords")


class SessionWarmupCandidate(BaseAiModel):
    """Candidate representation for session warmup generation."""

    word_display: str = Field(alias="wordDisplay")
    lemma: str
    part_of_speech: str = Field(alias="partOfSpeech")
    meaning_vi: str = Field(alias="meaningVi")


class SessionWarmupInput(BaseAiModel):
    """Request payload for generating introductory warmup stories for a study session."""

    candidates: list[SessionWarmupCandidate]


class SessionWarmupResult(BaseAiModel):
    """Response payload containing generated warmup trivia stories."""

    facts: list[WarmupFactStory]
