"""initial_schema

Revision ID: 2fe341dff1b3
Revises: 
Create Date: 2026-09-16 06:08:11.389975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fe341dff1b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext";')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DISABLED', name='user_status'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('current_cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', postgresql.CITEXT(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('refresh_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_session_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['replaced_by_session_id'], ['refresh_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('replaced_by_session_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='tutor_session_status'), nullable=False),
    sa.Column('target_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('target_activity_count', sa.Integer(), nullable=False),
    sa.Column('new_word_target', sa.Integer(), nullable=False),
    sa.Column('warmup_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_sessions_user_id'), 'tutor_sessions', ['user_id'], unique=False)
    op.create_table('vocabulary_collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_collections_user_id'), 'vocabulary_collections', ['user_id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', postgresql.CITEXT(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author_name', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_analysis_status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='ai_generation_status'), nullable=True),
    sa.Column('ai_analysis_error', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='article_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('article_sentences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('sentence_order', sa.Integer(), nullable=False),
    sa.Column('sentence_text', sa.Text(), nullable=False),
    sa.Column('translation_vi', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_article_progress',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_article_progress_article_id'), 'user_article_progress', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_article_progress_user_id'), 'user_article_progress', ['user_id'], unique=False)
    op.create_table('article_sentence_terms',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('lemma', sa.Text(), nullable=False),
    sa.Column('part_of_speech', sa.Text(), nullable=True),
    sa.Column('ipa', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=True),
    sa.Column('contextual_meaning_vi', sa.Text(), nullable=True),
    sa.Column('definition_en', sa.Text(), nullable=True),
    sa.Column('contextual_explanation', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('antonyms', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('collocations', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('related_terms', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origin', sa.Enum('MANUAL', 'AI', 'NLP', name='term_origin'), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='term_review_status'), nullable=False),
    sa.Column('explanation_status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='ai_generation_status'), nullable=False),
    sa.Column('explanation_error', sa.Text(), nullable=True),
    sa.Column('is_lookup_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['article_sentences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_vocabularies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('article_sentence_term_id', sa.UUID(), nullable=False),
    sa.Column('saved_word_display', sa.Text(), nullable=False),
    sa.Column('saved_lemma', sa.Text(), nullable=False),
    sa.Column('saved_part_of_speech', sa.Text(), nullable=False),
    sa.Column('saved_ipa', sa.Text(), nullable=True),
    sa.Column('saved_cefr_level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='cefr_level'), nullable=False),
    sa.Column('saved_meaning_vi', sa.Text(), nullable=False),
    sa.Column('definition_en', sa.Text(), nullable=True),
    sa.Column('saved_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fsrs_state', sa.Enum('NEW', 'LEARNING', 'REVIEW', 'RELEARNING', name='fsrs_card_state'), nullable=False),
    sa.Column('fsrs_stability', sa.Float(), nullable=True),
    sa.Column('fsrs_difficulty', sa.Float(), nullable=True),
    sa.Column('fsrs_scheduled_days', sa.Integer(), nullable=False),
    sa.Column('fsrs_learning_steps', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('lapse_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_sentence_term_id'], ['article_sentence_terms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_vocabularies_article_sentence_term_id'), 'user_vocabularies', ['article_sentence_term_id'], unique=False)
    op.create_index(op.f('ix_user_vocabularies_user_id'), 'user_vocabularies', ['user_id'], unique=False)
    op.create_table('tutor_session_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_vocabulary_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANSWERED', 'SKIPPED', name='tutor_session_item_status'), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'CONTEXTUAL_CLOZE', 'TYPED_RECALL', 'MICRO_LESSON_RETEST', name='tutor_question_type'), nullable=False),
    sa.Column('is_new_word', sa.Boolean(), nullable=False),
    sa.Column('question_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grading_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('fsrs_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_vi', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_vocabulary_id'], ['user_vocabularies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_session_items_session_id'), 'tutor_session_items', ['session_id'], unique=False)
    op.create_table('vocabulary_collection_items',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_vocabulary_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['vocabulary_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_vocabulary_id'], ['user_vocabularies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'user_vocabulary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_collection_items')
    op.drop_index(op.f('ix_tutor_session_items_session_id'), table_name='tutor_session_items')
    op.drop_table('tutor_session_items')
    op.drop_index(op.f('ix_user_vocabularies_user_id'), table_name='user_vocabularies')
    op.drop_index(op.f('ix_user_vocabularies_article_sentence_term_id'), table_name='user_vocabularies')
    op.drop_table('user_vocabularies')
    op.drop_table('article_sentence_terms')
    op.drop_index(op.f('ix_user_article_progress_user_id'), table_name='user_article_progress')
    op.drop_index(op.f('ix_user_article_progress_article_id'), table_name='user_article_progress')
    op.drop_table('user_article_progress')
    op.drop_table('article_sentences')
    op.drop_table('articles')
    op.drop_index(op.f('ix_vocabulary_collections_user_id'), table_name='vocabulary_collections')
    op.drop_table('vocabulary_collections')
    op.drop_index(op.f('ix_tutor_sessions_user_id'), table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
